import { PatientDataType } from "./tablecolumns/patientListTable"
export const patientDummyData: PatientDataType[] = [
    {
      key: '1',
      SN: '1',
      UHID: 'UH123456',
      patientName: 'John Brown',
    //   age: 32,
      agegender: 'Male/32',
      mobileNo: '123-456-7890',
      address: 'New York No. 1 Lake Park',
      patientType: 'Outpatient',
      registerDate: '2023-01-01',
      department: 'Cardiology',
    },
    {
      key: '2',
      SN: '2',
      UHID: 'UH123457',
      patientName: 'Jim Green',
    //   age: 42,
      agegender: 'Male/42',
      mobileNo: '123-456-7891',
      address: 'London No. 1 Lake Park',
      patientType: 'Inpatient',
      registerDate: '2023-02-01',
      department: 'Neurology',
    },
    {
      key: '3',
      SN: '3',
      UHID: 'UH123458',
      patientName: 'Joe Black',
    //   age: 32,
      agegender: 'Male/32',
      mobileNo: '123-456-7892',
      address: 'Sydney No. 1 Lake Park',
      patientType: 'Outpatient',
      registerDate: '2023-03-01',
      department: 'Orthopedics',
    },
    {
      key: '4',
      SN: '4',
      UHID: 'UH123459',
      patientName: 'Jane Smith',
    //   age: 29,
      agegender: 'Female/29',
      mobileNo: '123-456-7893',
      address: 'Tokyo No. 2 Lake Park',
      patientType: 'Inpatient',
      registerDate: '2023-04-01',
      department: 'Pediatrics',
    },
    {
      key: '5',
      SN: '5',
      UHID: 'UH123460',
      patientName: 'Mary Johnson',
    //   age: 38,
      agegender: 'Female/38', 
      mobileNo: '123-456-7894',
      address: 'Paris No. 3 Lake Park',
      patientType: 'Outpatient',
      registerDate: '2023-05-01',
      department: 'Dermatology',
    },
  ]